final Map<String, List<String>> checklists = {
  'AS InFlight New Hire Dedicated (FULL KIT)': [
    'Verify the Alaska Asset label and Device Identifiers on the IMD.',
    'Ensure that the Serial and IMEI numbers match those displayed in the IMD\'s settings.',
    'Confirm that the device is staged as "STAGING.ASIF.PREDEPLOY".',
    'Check if Location Services are enabled on the IMD.',
    'Ensure the IMD has the most current version of iOS installed.',
    'Confirm the installation of the HUB application.',
    'Verify the cellular connection is operational with the requested carrier.',
    'Ensure GoodReader is configured properly.',
    'Confirm that the Otterbox case is securely on the IMD.',
    'Verify MagTek name added to BlueFin.',
    'Set MagTek to "Activating" BlueFin.',
    'Confirm MagTek clip is on.',
    'Confirm MagTek is attached.',
    'Ensure the presence of the Apple charging brick (20W) and cable.',
    'Shut down device & Record Battery %.',
    'Ensure the device is packaged properly for safe shipping.',
    'Confirm the task number and all required labeling are on the shipping box.',
    'Verify the device\'s updated information within Odoo.',
  ],
  'AS InFlight New SHARED (Full Kit)': [
    'Verify the Alaska Asset label and Device Identifiers on the IMD.',
    'Ensure that the Serial and IMEI numbers match those displayed in the IMD\'s settings.',
    'Confirm that the device is staged as "staging.asif.loaner".',
    'Check if Location Services are enabled on the IMD.',
    'Ensure the IMD has the most current version of iOS installed.',
    'Confirm the installation of the HUB application.',
    'Verify the cellular connection is operational with the requested carrier.',
    'Ensure GoodReader is configured properly.',
    'Confirm that the Otterbox case is securely on the IMD.',
    'Verify MagTek name added to BlueFin.',
    'Set MagTek to "Activating" BlueFin.',
    'Confirm MagTek clip is on.',
    'Confirm MagTek is attached.',
    'Ensure the presence of the Apple charging brick (20W) and cable.',
    'Shut down device & Record Battery %.',
    'Ensure the device is packaged properly for safe shipping.',
    'Confirm the task number and all required labeling are on the shipping box.',
    'Verify the device\'s updated information within Odoo.',
  ],
  'AS Break Fix Dedicated (Full Kit)': [
    'Verify the Alaska Asset label and Device Identifiers on the IMD.',
    'Ensure that the Serial and IMEI numbers match those displayed in the IMD\'s settings.',
    'Confirm that the device is staged as "STAGING.ASIF.PREDEPLOY".',
    'Check if Location Services are enabled on the IMD.',
    'Ensure the IMD has the most current version of iOS installed.',
    'Confirm the installation of the HUB application.',
    'Verify the cellular connection is operational with the requested carrier.',
    'Ensure GoodReader is configured properly.',
    'Confirm that the Otterbox case is securely on the IMD.',
    'Verify MagTek name added to BlueFin.',
    'Set MagTek to "Activating" BlueFin.',
    'Confirm MagTek clip is on.',
    'Confirm MagTek is attached.',
    'Ensure the presence of the Apple charging brick (20W) and cable.',
    'Shut down device & Record Battery %.',
    'Ensure the device is packaged properly for safe shipping.',
    'Confirm the task number and all required labeling are on the shipping box.',
    'Verify the device\'s updated information within Odoo.',
  ],
  'AS Break Fix Dedicated (Device ONLY Kit)': [
    'Verify the Alaska Asset label and Device Identifiers on the IMD.',
    'Ensure that the Serial and IMEI numbers match those displayed in the IMD\'s settings.',
    'Confirm that the device is staged as "STAGING.ASIF.PREDEPLOY".',
    'Check if Location Services are enabled on the IMD.',
    'Ensure the IMD has the most current version of iOS installed.',
    'Confirm the installation of the HUB application.',
    'Verify the cellular connection is operational with the requested carrier.',
    'Ensure GoodReader is configured properly.',
    'Confirm that the Otterbox case is securely on the IMD.',
    'Verify MagTek name added to BlueFin.',
    'Set MagTek to "Activating" BlueFin.',
    'Confirm MagTek clip is on.',
    'Confirm MagTek is attached.',
    'Ensure the presence of the Apple charging brick (20W) and cable.',
    'Shut down device & Record Battery %.',
    'Ensure the device is packaged properly for safe shipping.',
    'Confirm the task number and all required labeling are on the shipping box.',
    'Verify the device\'s updated information within Odoo.',
  ],
  'AS Break Fix SHARED (DEVICE ONLY)': [
    'Verify the Alaska Asset label and Device Identifiers on the IMD.',
    'Ensure that the Serial and IMEI numbers match those displayed in the IMD\'s settings.',
    'Confirm that the device is staged as "staging.asif.loaner".',
    'Check if Location Services are enabled on the IMD.',
    'Ensure the IMD has the most current version of iOS installed.',
    'Confirm the installation of the HUB application.',
    'Verify the cellular connection is operational with the requested carrier.',
    'Ensure GoodReader is configured properly.',
    'Confirm that the Otterbox case is securely on the IMD.',
    'Verify MagTek name added to BlueFin.',
    'Set MagTek to "Activating" BlueFin.',
    'Confirm MagTek clip is on.',
    'Confirm MagTek is attached.',
    'Ensure the presence of the Apple charging brick (20W) and cable.',
    'Shut down device & Record Battery %.',
    'Ensure the device is packaged properly for safe shipping.',
    'Confirm the task number and all required labeling are on the shipping box.',
    'Verify the device\'s updated information within Odoo.',
  ],
  'AS InFlight CLASS Dedicated (FULL KIT)': [
    'Verify the Alaska Asset label and Device Identifiers on the IMD.',
    'Ensure that the Serial and IMEI numbers match those displayed in the IMD\'s settings.',
    'Confirm that the device is staged as "STAGING.ASINFLIGHT.CLASS".',
    'Check if Location Services are enabled on the IMD.',
    'Ensure the IMD has the most current version of iOS installed.',
    'Confirm the installation of the HUB application.',
    'Verify the cellular connection is operational with the requested carrier.',
    'Ensure GoodReader is configured properly.',
    'Confirm that the Otterbox case is securely on the IMD.',
    'Verify MagTek name added to BlueFin.',
    'Set MagTek to "Activating" BlueFin.',
    'Confirm MagTek clip is on.',
    'Confirm MagTek is attached.',
    'Ensure the presence of the Apple charging brick (20W) and cable.',
    'Shut down device & Record Battery %.',
    'Ensure the device is packaged properly for safe shipping.',
    'Confirm the task number and all required labeling are on the shipping box.',
    'Verify the device\'s updated information within Odoo.',
  ],
  'QX InFlight New Hire Dedicated (FULL KIT)': [
    'Verify the Alaska Asset label and Device Identifiers on the IMD.',
    'Ensure that the Serial and IMEI numbers match those displayed in the IMD\'s settings.',
    'Confirm that the device is staged as "STAGING.QXIF.PREDEPLOY".',
    'Check if Location Services are enabled on the IMD.',
    'Ensure the IMD has the most current version of iOS installed.',
    'Confirm the installation of the HUB application.',
    'Verify the cellular connection is operational with the requested carrier.',
    'Confirm that the Otterbox case is securely on the IMD.',
    'Verify MagTek name added to BlueFin.',
    'Set MagTek to "Activating" BlueFin.',
    'Confirm MagTek clip is on.',
    'Confirm MagTek is attached.',
    'Ensure the presence of the Apple charging brick (20W) and cable.',
    'Shut down device & Record Battery %.',
    'Ensure the device is packaged properly for safe shipping.',
    'Confirm the task number and all required labeling are on the shipping box.',
    'Verify the device\'s updated information within Odoo.',
  ],
  'QX InFlight New SHARED (Full Kit)': [
    'Verify the Alaska Asset label and Device Identifiers on the IMD.',
    'Ensure that the Serial and IMEI numbers match those displayed in the IMD\'s settings.',
    'Confirm that the device is staged as "staging.qxfa.loaner".',
    'Check if Location Services are enabled on the IMD.',
    'Ensure the IMD has the most current version of iOS installed.',
    'Confirm the installation of the HUB application.',
    'Verify the cellular connection is operational with the requested carrier.',
    'Confirm that the Otterbox case is securely on the IMD.',
    'Verify MagTek name added to BlueFin.',
    'Set MagTek to "Activating" BlueFin.',
    'Confirm MagTek clip is on.',
    'Confirm MagTek is attached.',
    'Ensure the presence of the Apple charging brick (20W) and cable.',
    'Shut down device & Record Battery %.',
    'Ensure the device is packaged properly for safe shipping.',
    'Confirm the task number and all required labeling are on the shipping box.',
    'Verify the device\'s updated information within Odoo.',
  ],
  'QX Break Fix Dedicated (Full Kit)': [
    'Verify the Alaska Asset label and Device Identifiers on the IMD.',
    'Ensure that the Serial and IMEI numbers match those displayed in the IMD\'s settings.',
    'Confirm that the device is staged as "STAGING.QXIF.PREDEPLOY".',
    'Check if Location Services are enabled on the IMD.',
    'Ensure the IMD has the most current version of iOS installed.',
    'Confirm the installation of the HUB application.',
    'Verify the cellular connection is operational with the requested carrier.',
    'Confirm that the Otterbox case is securely on the IMD.',
    'Verify MagTek name added to BlueFin.',
    'Set MagTek to "Activating" BlueFin.',
    'Confirm MagTek clip is on.',
    'Confirm MagTek is attached.',
    'Ensure the presence of the Apple charging brick (20W) and cable.',
    'Shut down device & Record Battery %.',
    'Ensure the device is packaged properly for safe shipping.',
    'Confirm the task number and all required labeling are on the shipping box.',
    'Verify the device\'s updated information within Odoo.',
  ],
  'QX Break Fix Dedicated (Device ONLY Kit)': [
    'Verify the Alaska Asset label and Device Identifiers on the IMD.',
    'Ensure that the Serial and IMEI numbers match those displayed in the IMD\'s settings.',
    'Confirm that the device is staged as "STAGING.QXIF.PREDEPLOY".',
    'Check if Location Services are enabled on the IMD.',
    'Ensure the IMD has the most current version of iOS installed.',
    'Confirm the installation of the HUB application.',
    'Verify the cellular connection is operational with the requested carrier.',
    'Confirm that the Otterbox case is securely on the IMD.',
    'Verify MagTek name added to BlueFin.',
    'Set MagTek to "Activating" BlueFin.',
    'Confirm MagTek clip is on.',
    'Confirm MagTek is attached.',
    'Ensure the presence of the Apple charging brick (20W) and cable.',
    'Shut down device & Record Battery %.',
    'Ensure the device is packaged properly for safe shipping.',
    'Confirm the task number and all required labeling are on the shipping box.',
    'Verify the device\'s updated information within Odoo.',
  ],
  'QX Break Fix SHARED (DEVICE ONLY)': [
    'Verify the Alaska Asset label and Device Identifiers on the IMD.',
    'Ensure that the Serial and IMEI numbers match those displayed in the IMD\'s settings.',
    'Confirm that the device is staged as "staging.qxfa.loaner".',
    'Check if Location Services are enabled on the IMD.',
    'Ensure the IMD has the most current version of iOS installed.',
    'Confirm the installation of the HUB application.',
    'Verify the cellular connection is operational with the requested carrier.',
    'Confirm that the Otterbox case is securely on the IMD.',
    'Verify MagTek name added to BlueFin.',
    'Set MagTek to "Activating" BlueFin.',
    'Confirm MagTek clip is on.',
    'Confirm MagTek is attached.',
    'Ensure the presence of the Apple charging brick (20W) and cable.',
    'Shut down device & Record Battery %.',
    'Ensure the device is packaged properly for safe shipping.',
    'Confirm the task number and all required labeling are on the shipping box.',
    'Verify the device\'s updated information within Odoo.',
  ],
  'QX InFlight CLASS Dedicated (FULL KIT)': [
    'Verify the Alaska Asset label and Device Identifiers on the IMD.',
    'Ensure that the Serial and IMEI numbers match those displayed in the IMD\'s settings.',
    'Confirm that the device is staged as "STAGING.QXIF.PREDEPLOY".',
    'Check if Location Services are enabled on the IMD.',
    'Ensure the IMD has the most current version of iOS installed.',
    'Confirm the installation of the HUB application.',
    'Verify the cellular connection is operational with the requested carrier.',
    'Confirm that the Otterbox case is securely on the IMD.',
    'Verify MagTek name added to BlueFin.',
    'Set MagTek to "Activating" BlueFin.',
    'Confirm MagTek clip is on.',
    'Confirm MagTek is attached.',
    'Ensure the presence of the Apple charging brick (20W) and cable.',
    'Shut down device & Record Battery %.',
    'Ensure the device is packaged properly for safe shipping.',
    'Confirm the task number and all required labeling are on the shipping box.',
    'Verify the device\'s updated information within Odoo.',
  ],
};
