final Map<String, Map<String, String>> statements = {
  'IPHONE 12': {
    'DEV': 'Statement for IPHONE 12, DEV',
    'ITS': 'Statement for IPHONE 12, ITS',
    'OTHER': 'Statement for IPHONE 12, OTHER',
    'AS InFlight New Hire Dedicated (FULL KIT)': 'Statement for IPHONE 12, AS InFlight New Hire Dedicated (FULL KIT)',
    'AS InFlight New SHARED (Full Kit)': 'Statement for IPHONE 12, AS InFlight New SHARED (Full Kit)',
    'AS Break Fix Dedicated (Full Kit)': 'Statement for IPHONE 12, AS Break Fix Dedicated (Full Kit)',
    'AS Break Fix Dedicated (Device ONLY Kit)': 'Statement for IPHONE 12, AS Break Fix Dedicated (Device ONLY Kit)',
    'AS Break Fix SHARED (DEVICE ONLY)': 'Statement for IPHONE 12, AS Break Fix SHARED (DEVICE ONLY)',
    'AS InFlight CLASS Dedicated (FULL KIT)': 'Statement for IPHONE 12, AS InFlight CLASS Dedicated (FULL KIT)',
    'QX InFlight New Hire Dedicated (FULL KIT)': 'Statement for IPHONE 12, QX InFlight New Hire Dedicated (FULL KIT)',
    'QX InFlight New SHARED (Full Kit)': 'Statement for IPHONE 12, QX InFlight New SHARED (Full Kit)',
    'QX Break Fix Dedicated (Full Kit)': 'Statement for IPHONE 12, QX Break Fix Dedicated (Full Kit)',
    'QX Break Fix Dedicated (Device ONLY Kit)': 'Statement for IPHONE 12, QX Break Fix Dedicated (Device ONLY Kit)',
    'QX Break Fix SHARED (DEVICE ONLY)': 'Statement for IPHONE 12, QX Break Fix SHARED (DEVICE ONLY)',
    'QX InFlight CLASS Dedicated (FULL KIT)': 'Statement for IPHONE 12, QX InFlight CLASS Dedicated (FULL KIT)',
  },
  'IPHONE 13': {
    'DEV': 'Statement for IPHONE 13, DEV',
    'ITS': 'Statement for IPHONE 13, ITS',
    'OTHER': 'Statement for IPHONE 13, OTHER',
    'AS InFlight New Hire Dedicated (FULL KIT)': 'Statement for IPHONE 13, AS InFlight New Hire Dedicated (FULL KIT)',
    'AS InFlight New SHARED (Full Kit)': 'Statement for IPHONE 13, AS InFlight New SHARED (Full Kit)',
    'AS Break Fix Dedicated (Full Kit)': 'Statement for IPHONE 13, AS Break Fix Dedicated (Full Kit)',
    'AS Break Fix Dedicated (Device ONLY Kit)': 'Statement for IPHONE 13, AS Break Fix Dedicated (Device ONLY Kit)',
    'AS Break Fix SHARED (DEVICE ONLY)': 'Statement for IPHONE 13, AS Break Fix SHARED (DEVICE ONLY)',
    'AS InFlight CLASS Dedicated (FULL KIT)': 'Statement for IPHONE 13, AS InFlight CLASS Dedicated (FULL KIT)',
    'QX InFlight New Hire Dedicated (FULL KIT)': 'Statement for IPHONE 13, QX InFlight New Hire Dedicated (FULL KIT)',
    'QX InFlight New SHARED (Full Kit)': 'Statement for IPHONE 13, QX InFlight New SHARED (Full Kit)',
    'QX Break Fix Dedicated (Full Kit)': 'Statement for IPHONE 13, QX Break Fix Dedicated (Full Kit)',
    'QX Break Fix Dedicated (Device ONLY Kit)': 'Statement for IPHONE 13, QX Break Fix Dedicated (Device ONLY Kit)',
    'QX Break Fix SHARED (DEVICE ONLY)': 'Statement for IPHONE 13, QX Break Fix SHARED (DEVICE ONLY)',
    'QX InFlight CLASS Dedicated (FULL KIT)': 'Statement for IPHONE 13, QX InFlight CLASS Dedicated (FULL KIT)',
  },
  'IPHONE 15': {
    'Refresh': 'Statement for IPHONE 15, Refresh',
    'DEV': 'Statement for IPHONE 15, DEV',
    'ITS': 'Statement for IPHONE 15, ITS',
    'OTHER': 'Statement for IPHONE 15, OTHER',
    'AS InFlight New Hire Dedicated (FULL KIT)': 'Statement for IPHONE 15, AS InFlight New Hire Dedicated (FULL KIT)',
    'AS InFlight New SHARED (Full Kit)': 'Statement for IPHONE 15, AS InFlight New SHARED (Full Kit)',
    'AS Break Fix Dedicated (Full Kit)': 'Statement for IPHONE 15, AS Break Fix Dedicated (Full Kit)',
    'AS Break Fix Dedicated (Device ONLY Kit)': 'Statement for IPHONE 15, AS Break Fix Dedicated (Device ONLY Kit)',
    'AS Break Fix SHARED (DEVICE ONLY)': 'Statement for IPHONE 15, AS Break Fix SHARED (DEVICE ONLY)',
    'AS InFlight CLASS Dedicated (FULL KIT)': 'Statement for IPHONE 15, AS InFlight CLASS Dedicated (FULL KIT)',
    'QX InFlight New Hire Dedicated (FULL KIT)': 'Statement for IPHONE 15, QX InFlight New Hire Dedicated (FULL KIT)',
    'QX InFlight New SHARED (Full Kit)': 'Statement for IPHONE 15, QX InFlight New SHARED (Full Kit)',
    'QX Break Fix Dedicated (Full Kit)': 'Statement for IPHONE 15, QX Break Fix Dedicated (Full Kit)',
    'QX Break Fix Dedicated (Device ONLY Kit)': 'Statement for IPHONE 15, QX Break Fix Dedicated (Device ONLY Kit)',
    'QX Break Fix SHARED (DEVICE ONLY)': 'Statement for IPHONE 15, QX Break Fix SHARED (DEVICE ONLY)',
    'QX InFlight CLASS Dedicated (FULL KIT)': 'Statement for IPHONE 15, QX InFlight CLASS Dedicated (FULL KIT)',
  },
};
